[project]
name = "climatempo"
version = "0.1.0"
description = ""
authors = [
    {name = "Sarah Janne",email = "sarahjanne.enos@hotmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "fastapi",
    "requests (>=2.32.0,<3.0.0)",
    "uvicorn (>=0.53.0,<0.54.0)"
]

[tool.poetry]
packages = [
    { include = "controllers" },
    { include = "schemas" },
    { include = "services" },
    { include = "main.py" }
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
